Fixes an issue where part of the selected node border would stay visible
git-up/GitUp pull request #716
Opened 2020-11-24 22:26 UTC by zwaldowski

Fixes a math issue where the rim of a selected node would still be visible on a retina display under certain conditions.

Image of the issue (squint hard!)

<img width="427" alt="Screen Shot 2020-11-24 at 5 16 39 PM" src="https://user-images.githubusercontent.com/170812/100158459-341aee00-2e7a-11eb-889d-8037085d37a5.png">

2020-11-27 00:31 UTC, lucasderraugh commented
I believe this actually addressed #654. Somebody will be happy 😀

2020-11-27 00:37 UTC, lucasderraugh commented
Is this issue here just that the pixel boundaries aren't exact? Should it be instead flooring/rounding the `y` input?

2020-11-27 01:40 UTC, zwaldowski commented
I initially thought it was just a rounding issue, and applied an alignment method on it; but it doesn’t help. It does seem instead to be that the formula doesn’t account for the border.

2020-12-01 14:52 UTC, lucasderraugh commented
@zwaldowski Did you ever find a good way to reproduce this issue? Is there a way to always reproduce this issue if you changed an aspect of how the bubble was drawn? I was just hoping to have some repro steps to test out the changes.

2020-12-01 17:27 UTC, zwaldowski commented
Sure. It happens consistently on the tip of [this repo](https://github.com/zwaldowski/semver-release-action/issues/12) in Dark Mode when Virtual Branch Tips is ON and Stale Branch Tips is ON. It appears to happen when the rect for a selection straddles one of the system’s tile sizes. It can be exacerbated by changing the selection border width (GIGraphView.m:1369), but that alone does not make it happen on every node.

2020-12-02 15:13 UTC, lucasderraugh requested changes

2020-12-02 15:13 UTC, lucasderraugh commented on GitUpKit/Interface/GIGraphView.m
> +#define SELECTED_NODE_BOUNDS(x, y) NSMakeRect(x - kSpacingX / 2, y - (kSelectedLabelMaxHeight / 2) - kSubLineWidth, kSelectedLabelMaxWidth + kSpacingX / 2 + 40, kSelectedLabelMaxHeight + (kSubLineWid
I think kSubLineWidth changes the width of the lines between nodes, I don't believe that controls border width. Probably shouldn't use that, but I'm fine with making a new constant that reflects this value.

2020-12-03 16:56 UTC, lucasderraugh approved these changes
Thanks

2020-12-03 16:56 UTC, merged