Added AskSetUpstreamOnPush property
git-up/GitUp pull request #786
Opened 2021-11-30 21:09 UTC by NikKovIos

If true when push there is an al…ert to ask set upstream. If false there are no alerts, upstream setted automaticly.

2021-11-30 21:35 UTC, lucasderraugh requested changes
Thanks for the contribution! A few things I'd change before approval:

- Could we move this setting to be just below "Commits:" section in the preferences. I think it's more logical there than after text changes.
- Let's make the text: "Ask to set upstream on push"

Other than that I'll test it out to see how it works.

2021-11-30 21:39 UTC, NikKovIos commented
@lucasderraugh before i fix that, could you please test this functional?

2021-11-30 21:52 UTC, lucasderraugh requested changes
Looks like the radio buttons around "Diff Generation:" also go messed up. If you compare the preferences from your build to master it is offset.

Other than these issues, I think the flow itself works well though.

2021-11-30 21:52 UTC, lucasderraugh commented on GitUpKit/Views/GIMapViewController+Operations.m
> +            BOOL askSetUpstreamOnPushSetting = [[NSUserDefaults standardUserDefaults] boolForKey:kUserDefaultsKey_AskSetUpstreamOnPush];
Let's also call this simply `askSetUpstreamOnPush` as that is more of a boolean statement.

2021-12-01 11:58 UTC, NikKovIos commented
- "Ask to set upstream on push" - renamed
- below "Commits" - done
- radio buttons around "Diff Generation:" - i've aligned them, there vas a bug
- askSetUpstreamOnPushSetting renamed

2021-12-01 12:01 UTC, NikKovIos commented
Now it looks:
<img width="612" alt="Снимок экрана 2021-12-01 в 15 00 38" src="https://user-images.githubusercontent.com/16647690/144230955-bcd7693a-d9fd-4c56-9ee0-84d405e1125f.png">

2021-12-01 13:47 UTC, lucasderraugh commented
The "Diff Generation:" text seems incorrectly offset with the radio buttons compared to the current layout:
<img width="612" alt="Screen Shot 2021-12-01 at 8 47 13 AM" src="https://user-images.githubusercontent.com/714282/144245625-05558718-cfe3-4a7a-8002-7d9c4a513e8f.png">
.

2021-12-01 14:06 UTC, NikKovIos commented
@lucasderraugh indeed! It's in release now. I've fixed it in this MR and placed a screenshot. Did you try to build it?

2021-12-01 14:10 UTC, NikKovIos commented
Did correct "Diff generation" label.

2021-12-06 11:27 UTC, NikKovIos commented
@lucasderraugh maybe merge?)

2021-12-06 18:07 UTC, lucasderraugh requested changes
Last change is to make these items lowercase, then I'll merge it in.

2021-12-06 18:07 UTC, lucasderraugh commented on GitUp/Application/Base.lproj/PreferencesWindowController.xib
> +                                            <buttonCell key="cell" type="check" title="Ask to Set Upstream on push" bezelStyle="regularSquare" imagePosition="left" state="on" inset="2" id="Wi7-L1-z3w
```suggestion
                                            <buttonCell key="cell" type="check" title="Ask to set upstream on push" bezelStyle="regularSquare" imagePosition="left" state="on" inset="2" id="Wi7-L1-z3w">
```

2021-12-06 18:15 UTC, merged