Add key navigation between index and workdir files
git-up/GitUp pull request #921
Opened 2023-03-11 05:18 UTC by fo2rist

Navigate to index files controller when Down button pressed while on the last file of the workdir list
Navigate to workdir files controller when Up button pressed while on the first files of the index list

**Context**: I'm using keyboard navigation for most of the actions in GitUp but there were no way to quickly navigate b/w staged and un-staged files, and while it's possible with Tab/Shift+Tab it breaks natural up/down navigation that's available in simple mode. This change adds that ability to standard mode as well.

**Testing and considerations**:
- I checked that simple mode still works the same as before
- I added checks to make sure there is not confusing behavior when Arrow key is pressed with a modifier or when multiple files selected to avoid losing selection
- I added checks to prevent navigation to an empty list
- No changes to the documentation page is needed since it simply mentions `Arrow up & Arrow down to select a different file` which is still true

2023-03-11 05:20 UTC, fo2rist commented
Would like to discuss a possibility to add arrow navigation between individual lines in the diff view.
That would allow me to do complete change/review/commit cycle with keyboard.

2023-03-12 16:30 UTC, lucasderraugh commented
Thanks for writing this up. I'll take some time tonight or tomorrow to review what's being changed here.

2023-04-15 20:06 UTC, lucasderraugh requested changes
Apologies for the delay in reviewing this. Looks good to me and welcome functionality.
Small nits just to change the type to match the `modifierFlags` property.
I was also thinking if there was an easier way to just say there were no modifiers, but I guess it includes caps lock and things like that, so this looks appropriate.

Other than that, it's ready to merge.

2023-04-15 20:06 UTC, lucasderraugh commented on GitUpKit/Interface/GIConstants.h
> +static const long kGIKeyModifiersAll = NSEventModifierFlagShift | NSEventModifierFlagControl | NSEventModifierFlagCommand | NSEventModifierFlagOption;
```suggestion
static const NSEventModifierFlags kGIKeyModifiersAll = NSEventModifierFlagShift | NSEventModifierFlagControl | NSEventModifierFlagCommand | NSEventModifierFlagOption;
```

2023-04-15 20:06 UTC, lucasderraugh commented on GitUpKit/Views/GIAdvancedCommitViewController.m
> +  long modifiers = event.modifierFlags & kGIKeyModifiersAll;
```suggestion
  NSEventModifierFlags modifiers = event.modifierFlags & kGIKeyModifiersAll;
```

2023-05-14 03:38 UTC, fo2rist commented on GitUpKit/Interface/GIConstants.h
> +static const long kGIKeyModifiersAll = NSEventModifierFlagShift | NSEventModifierFlagControl | NSEventModifierFlagCommand | NSEventModifierFlagOption;
Done

2023-05-26 15:18 UTC, lucasderraugh approved these changes

2023-05-26 15:18 UTC, merged