Explain: Brew install
git-up/GitUp pull request #940
Opened 2023-07-24 17:01 UTC by mathiash98

Explain how to actually get started by downloading from either the official website (not really a source of download as github releases is used instead). Or by using homebrew.

Closes #904

2023-07-25 11:56 UTC, lucasderraugh commented
@mathiash98 Thanks for the PR. I'm away from my computer for 2 weeks, but this can mostly be done via my phone. The one addition I'd like made here is to explicitly say that GitUp maintainers do not maintain the Homebrew Cask.

2023-07-26 05:12 UTC, beatrupp approved these changes

2023-07-26 12:09 UTC, lucasderraugh requested changes
Just small spelling correction and good to go.

2023-07-26 12:09 UTC, lucasderraugh commented on README.md
> +- Homebrew (Not mantained by GitUp developers): `brew install homebrew/cask/gitup` (Note: There is already a formula called gitup, so the full name must be specified!)
```suggestion
- Homebrew (Not maintained by GitUp developers): `brew install homebrew/cask/gitup` (Note: There is already a formula called gitup, so the full name must be specified!)
```

2023-07-26 12:25 UTC, merged